### ISSUE TITLE
Integration scenario with SAML authentication

### ISSUE THREAD

**Issue by bcolas** [pentaho/pentaho-engineering-samples#59]
While accessing the URL https://my_pentaho_server/pentaho/  leads  to ADFS login page, trying to access directly a report or a cde dashboard (for example https://my_pentaho_server/pentaho/api/repos...) or integration resources (https://_my_pentaho_server_/pentaho/plugin/pentaho-cdf-dd/api/renderer/cde-embed.js?protocol=HTTPS&port=443), pops up a authentification windows and not use SAML authentification process

**Comment by pamval** [comment]
What Pentaho version are you using?

**Comment by bcolas** [comment]
I am using Pentaho CE 6.1

I tried to modify bean "filterChainProxy" in pentaho-solutions/system/applicationContext-spring-security-saml.xml with no success

Benoit

**Comment by bcolas** [comment]
In debug, accessing the ressource https://my_pentaho_server/pentaho/**plugin**/pentaho-cdf-dd/api/renderer/cde-embed.js gives
`DEBUG [org.springframework.security.providers.anonymous.AnonymousProcessingFilter] **Populated SecurityContextHolder with anonymous token**: 'org.springframework.security.providers.anonymous.AnonymousAuthenticationToken@449bbe51: Principal: anonymousUser; Password: [PROTECTED]; Authenticated: true; Details: org.springframework.security.ui.WebAuthenticationDetails@0: RemoteIpAddress: XXX.XXX.XXX.XXX; SessionId: CA58F9A0DA2DAD04528C3C0D4D9340E0; Granted Authorities: Anonymous'
`
Response headers are 
`HTTP/1.1 401 Non-Autorisé
Server: Apache-Coyote/1.1
Set-Cookie: JSESSIONID=2F9FDA0E6172CE8119BCB015BF8A9F96; Path=/pentaho/; HttpOnly
WWW-Authenticate: Basic realm="Pentaho Realm"
Content-Type: text/html;charset=utf-8
Content-Language: fr
Content-Length: 1117
Date: Thu, 15 Mar 2018 11:15:08 GMT
Strict-Transport-Security: max-age=157680000`

Note that accessing ressource https://my_pentaho_server/pentaho/**content**/pentaho-cdf-dd/js/cde-require-js-cfg.js has different behavior, no authentification popup is displayed

`DEBUG [org.springframework.security.providers.anonymous.AnonymousProcessingFilter] Populated SecurityContextHolder with anonymous token: 'org.springframework.security.providers.anonymous.AnonymousAuthenticationToken@449bbe51: Principal: anonymousUser; Password: [PROTECTED]; Authenticated: true; Details: org.springframework.security.ui.WebAuthenticationDetails@0: RemoteIpAddress: 10.252.138.72; SessionId: B9099D0E3B2B9F4CB46A796B08753A38; Granted Authorities: Anonymous'`

probably due to filterInvocationInterceptorForWS settings in pentaho-solutions/system/applicationContext-spring-security.xml settings
`<property name="objectDefinitionSource">
    <value>
        <![CDATA[CONVERT_URL_TO_LOWERCASE_BEFORE_COMPARISON
        ...
        \A/plugin/.*\Z=Authenticated
    ]]>
    </value>
</property>`

**Comment by bcolas** [comment]
If the resource is accessed after login via Home, the log trace is 
`DEBUG [org.springframework.security.providers.anonymous.AnonymousProcessingFilter] SecurityContextHolder not populated with anonymous token, as it already contained: 'org.springframework.security.providers.UsernamePasswordAuthenticationToken@2fe04395: Principal: _xxxx_@_yyyy_; Password: [PROTECTED]; Authenticated: true; Details: null; Granted Authorities: Authenticated'`

**Comment by bcolas** [comment]
@pamval : Any clue I can follow to solve my issue ?

**Comment by pedrofvteixeira** [comment]
Hi @bcolas, if I understood correctly your issue: 
- SAML authentication mechanism is working fine in scenarios where you access `URL https://my_pentaho_server/pentaho`
- Only when you directly access "deep links" such as `https://my_pentaho_server/pentaho/plugin/pentaho-cdf-dd/api/renderer/cde-embed.js` is where you notice you are still getting an authentication pop-up window and not the SAML authentication process 

Is this correct ? If so, then most likely this is related to the definition set for spring-security's filterChainProxy.

Can you please try this out on your end?

1. Open `pentaho-solutions/system/applicationContext-spring-security-saml.xml`
  1.1. - **First and foremost**, please copy it somewhere else, to keep as a backup, should you ever care for resetting any changes you'll be doing.
2. In the `filterChainProxy` definitions, you will notice that there are couple of lines, each holding a different URL pattern:  `/api/**=(...)` , `/plugin/**=(...)` , `/**=(...)` , ..
3. What you'd want to do is to make sure those lines mimic the one that is taking place when you hit `https://my_pentaho_server/pentaho` , which is `/**=(...)`
  3.1. Keep in mind that for the endpoint `https://my_pentaho_server/pentaho/plugin/pentaho-cdf-dd/api/renderer/cde-embed.js`, the line taking place is `/plugin/**=(...)`
  3.2. Notice how `/**=(...)` line holds `securityContextHolderAwareRequestFilter`, and that all other lines hold `securityContextHolderAwareRequestFilterForWS`
  3.3. So for line `/plugin/**=(...)`, replace `securityContextHolderAwareRequestFilterForWS` with `securityContextHolderAwareRequestFilter`
4. Save the file, restart the server, try hitting the endpoint `https://my_pentaho_server/pentaho/plugin/pentaho-cdf-dd/api/renderer/cde-embed.js` once again

Let me know how it goes.

Hope this helps,

Best regards,

Pedro Teixeira

**Comment by bcolas** [comment]
Hi @pedrofvteixeira 

First I thank you for your answer.
1. Your understanding of the problem I am trying to solve is **correct**
- SAML authentication mechanism is working fine in scenarios where I access URL https://my_pentaho_server/pentaho
- Only when I directly access "deep links" such as https://my_pentaho_server/pentaho/plugin/pentaho-cdf-dd/api/renderer/cde-embed.js, I notice I am getting an authentication pop-up window and not the SAML authentication process

2. Following your comment, I modified the config file `pentaho-solutions/system/applicationContext-spring-security-saml.xml` replacing on line `/plugin/**=(...)` `securityContextHolderAwareRequestFilterForWS` with `securityContextHolderAwareRequestFilter`
==> Behavior does not change and I still have a popup window for WWW-Authenticate: Basic realm="Pentaho Realm"

3. I did another test : I modified the config file `pentaho-solutions/system/applicationContext-spring-security-saml.xml` **deleting** line `/plugin/**=(...)`
==> SAML authentication process occurs but after logging in, redirection is done towards `https://my_pentaho_server/pentaho/Home` instead of my deep link `https://my_pentaho_server/pentaho/plugin/pentaho-cdf-dd/api/renderer/cde-embed.js`

4. Last test I did : 
4.1 I switched back to original version of `pentaho-solutions/system/applicationContext-spring-security-saml.xml` and I replaced `exceptionTranslationFilterForWS` with `exceptionTranslationFilter`
==> SAML authentication process occurs but after logging in, redirection is done towards homepage instead of my deep link
4.2 In the original version of `pentaho-solutions/system/applicationContext-spring-security-saml.xml` and I replaced `exceptionTranslationFilterForWS` with `exceptionTranslationFilter`
==> got a popup window for WWW-Authenticate: Basic realm="Pentaho Realm"

I noticed that in our config file `pentaho-solutions/system/applicationContext-spring-security-saml.xml` we have the following section
```
  <!-- overridden from applicationContext-spring-security.xml -->
  <bean id="exceptionTranslationFilter" class="org.springframework.security.ui.ExceptionTranslationFilter">
    <property name="authenticationEntryPoint">
      <ref bean="samlAuthenticationFilterEntryPoint" />
    </property>
    <property name="accessDeniedHandler">
      <bean class="org.springframework.security.ui.AccessDeniedHandlerImpl" />
    </property>
  </bean>
```

**Comment by pedrofvteixeira** [comment]
Hi @bcolas ,

- when SAML identification provider returns to us a 👍 , we trigger a RedirectHandler; nowadays, we redirect to Pentaho Server's standard `index.jsp` ( which you'd find located in your `<install-dir>/tomcat/webapps/pentaho` )
  - `index.jsp`, in turn, redirects to `/Home` 
  - https://github.com/pentaho/pentaho-engineering-samples/blob/6.1/Samples%20for%20Extending%20Pentaho/Reference%20Implementations/Security/SAML%202.0/pentaho-saml/src/main/resources/OSGI-INF/blueprint/blueprint.xml#L448-L450

If you'd like to give it a go, you can try a custom build of this SAML sample, where you replace in the blueprint.xml line above `<property name="defaultTargetUrl" value="/index.jsp"/>` with `<property name="defaultTargetUrl" value="<your_deep_link>"/>`. Rebuild the SAML sample and give it a try. Please always remind to backup your files prior to changing them.

**Comment by bcolas** [comment]
Hi @pedrofvteixeira

With your help, I forked the project to bcolas/pentaho-engineering-samples and made enhancements to made the redirection dynamic depending on the initial request.
It is now possible to request any Pentaho BA deep link, go through SAML authentification process and get the resource after successful login.

I don't know if you'd like me to pull request the changes, otherwise they are available in my forked repository

Thanks for all
Benoit

**Comment by pedrofvteixeira** [comment]
Hey @bcolas 

glad to hear the solution worked for you! 
Yes, if you can contribute to the SAML-Sample issuing a PR with the proposed changes, we would appreciate that, and will definitely look into it.

Best regards,

Pedro T.

**Comment by bcolas** [comment]
Pull Request #63 
Best regards - Benoit
